name: Deploy Frontend to Azure Static Web Apps (Simple)

on:
  push:
    branches: [ main ]
    paths:
      - 'pos-frontend/**'
      - '.github/workflows/frontend-azure-swa-simple.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pos-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          REACT_APP_API_URL: https://garments-pos-backend-v2.azurewebsites.net
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 0b0e06d7a7af298e0035523c1c0084139e56ee5ff2f36a48abdf00e3dfbb6e8002-95cc4c11-2021-4919-b1e5-1b01ed0f2e0d00f112309dd6700f
          app_location: "/pos-frontend"
          output_location: "build"

